# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=80)),
                ('create_user', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
